# CGR QIIME2 pipeline for microbiome analysis.
#
# AUTHORS:
#     S. Sevilla Chill
#     W. Zhou
#     B. Ballew
#     Y. Wan

## Manifest
metadata_manifest: 'config/test_manifest.txt'

## Input directory (CGR-generated data only)
fastq_abs_path: '/DCEG/CGF/Sequencing/Illumina/MiSeq/PostRun_Analysis/Data/'
temp_dir: '/scratch/bb/16s_test/'

## Run type
data_source: 'internal'  # 'external' or 'internal' (to CGR)

## Analysis parameters
dada2_denoise:
  trim_left_forward: 0
  trim_left_reverse: 0
  truncate_length_forward: 0
  truncate_length_reverse: 0
  min_fold_parent_over_abundance: 2.0
phred_score: 33
demux_param: 'paired_end_demux'
input_type: 'SampleData[PairedEndSequencesWithQuality]'
min_num_features_per_sample: 1
min_num_reads_per_sample: 1
min_num_reads_per_feature: 1
min_num_samples_per_feature: 1
sampling_depth: 10000
max_depth: 54000
reference_db:  # change based on qiime version
- '/DCEG/CGF/Bioinformatics/Production/Bari/refDatabases/scikit_0.20.2_q2_2019.1/gg-13-8-99-nb-classifier.qza'
- '/DCEG/CGF/Bioinformatics/Production/Bari/refDatabases/scikit_0.20.2_q2_2019.1/silva-132-99-nb-classifier.qza'

## Cluster submission parameters
cluster_mode: 'qsub -V -q seq-calling.q -cwd -j y -o results/logs/ -S /bin/bash -pe by_node {threads}'  # options are 'qsub/sbatch/etc ...', 'local', 'dryrun', 'unlock'
  # SGE example:    qsub -q myqueue.q -V -j y -S /bin/bash -o /path/to/project/directory/logs/ -pe by_node {threads}
  # slurm example:  sbatch --mem=64g --time=24:00:00 --output=/path/to/project/directory/logs/slurm-%j.out --cpus-per-task={threads}
num_jobs: 100
latency: 60
